# Generated by Django 5.0 on 2023-12-26 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('for_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable',
            name='password2',
        ),
    ]
