# Generated by Django 5.0 on 2023-12-29 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_users', '0002_remove_usertable_password2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='profile_image',
            field=models.ImageField(default='/static/for_users/img/cat_profile.jpg', upload_to='./static/for_users/img/'),
        ),
        migrations.AddField(
            model_name='usertable',
            name='user',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
