# Generated by Django 5.0 on 2023-12-29 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('for_users', '0003_usertable_profile_image_usertable_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable',
            name='user',
        ),
    ]
