# Generated by Django 5.0 on 2023-12-26 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_artiles_articles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
