# Generated by Django 5.0 on 2023-12-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FileField(default='img/1.jpg', upload_to='./static/img/'),
        ),
    ]
